DELETE FROM account WHERE id > 1000000;
DELETE FROM link_user WHERE id > 1000000;
DELETE FROM payment WHERE id > 1000000;

ALTER TABLE account AUTO_INCREMENT = 1;
ALTER TABLE link_user AUTO_INCREMENT = 1;
ALTER TABLE payment AUTO_INCREMENT = 1;